spring.application.name=digital-banking-services

spring.datasource.url=jdbc:postgresql://localhost:5432/digital_banking
spring.datasource.username=digital_banking
spring.datasource.password=digital_banking
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.devtools.add-properties=true