spring.application.name=digital-banking-services

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digital_banking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:digital_banking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:digital_banking}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.devtools.add-properties=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always