spring.application.name=insurance-services

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/insurance_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:insurance_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:insurance_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

risk.service.url=${RISK_SERVICE_URL:http://risk-service:8082}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
